package com.jimi.spring.framework.dataaccess.jdbc;

import org.springframework.boot.jdbc.DataSourceBuilder;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.PreparedStatementCreator;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * @author jimi
 * @version 1.0
 * @date 2020/7/24 10:48
 */
public class AutoGeneratedKeysDemo {
    private static final JdbcTemplate jdbcTemplate = new JdbcTemplate();

    static {
        jdbcTemplate.setDataSource(
                DataSourceBuilder.create()
                        .driverClassName("com.mysql.jdbc.Driver")
                        .url("jdbc:mysql://localhost:3306/sakila?useSSL=false&amp;allowPublicKeyRetrieval=true")
                        .username("root")
                        .password("90jimi@mysql")
                        .build());
    }
    public static void main(String[] args) {
        final String INSERT_SQL = "insert into my_test (name) values(?)";
        final String name = "Rob";
        KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbcTemplate.update(
                new PreparedStatementCreator() {
                    public PreparedStatement createPreparedStatement(Connection connection) throws SQLException {
                        PreparedStatement ps = connection.prepareStatement(INSERT_SQL, new String[] {"id"});
                        ps.setString(1, name);
                        return ps;
                    }
                },
                keyHolder);
    }
}
